### ISSUE TITLE
How to select database schema?

### ISSUE THREAD

**Issue by dangdennis** [com-lihaoyi/scalasql#14]
I have tables in schemas other than Postgres's `public.` schema. How would I define a `Table` with a different schema?

**Comment by lihaoyi** [comment]
does `override def tableName = "schemaname.tablename` on the table companion object work?

**Comment by dangdennis** [comment]
I tried that prior and it didn’t work. 

The issue was that the generated query used “auth.users0” in place of the actual name table.

**Comment by santanaraphael** [comment]
@dangdennis did you ever get a solution? I'm having the same issue, my schema is source and table is invoice. I tried setting the tableName as source.invoice, but whenever creating the selects, it tries to alias that table as source.invoice0, which is invalid SQL.

**Comment by santanaraphael** [comment]
hey @lihaoyi do you know of another workarounds?

**Comment by lihaoyi** [comment]
@santanaraphael I don't have any other workarounds off the top of my head, we might need to patch scalasql to add support for this

**Comment by lihaoyi** [comment]
Should be fixed by https://github.com/com-lihaoyi/scalasql/pull/23. I tagged 0.1.6 which should go out soon
