### ISSUE TITLE
Scala reflect error 

### ISSUE THREAD

**Issue by ruelshakya15** [com-lihaoyi/scalasql#16]
I tried importing the dependency using maven, I get this error "Could not find artifact org.scala-lang:scala-reflect:pom:scalasql[2.13.12].scalaVersion in central (https://repo.maven.apache.org/maven2)",
-tried different 2.13.x versions
-tried all the different versions of scalasql , Can I get some insights on how to fix this?

**Comment by lihaoyi** [comment]
Can you try 0.1.4? I just released that with changes that should fix this error

**Comment by ruelshakya15** [comment]
Yes seems like its fine now
