### ISSUE TITLE
Scala 3 Support (1000USD Bounty)

### ISSUE THREAD

**Issue by lihaoyi** [com-lihaoyi/scalasql#2]
Currently ScalaSql only supports Scala 2.13. Getting it working on Scala 3 would involve porting the table macros, which is one ~100 line file https://github.com/com-lihaoyi/scalasql/blob/main/scalasql/query/src-2/TableMacro.scala. I don't have the knowledge of Scala 3 macros to do it myself, but it shouldn't be hard to port, and the rest of the ScalaSql library should "just work".

To incentivize contribution, I'm putting a 1000USD bounty on resolving this ticket to the first person who can get all the ScalaSql tests passing on Scala 3. This is payable via bank transfer, and at my discretion in case of ambiguity.

**Comment by lihaoyi** [comment]
@KuceraMartin said he wanted to look into this, but if anyone else wants to try their hand at this free free to do so

**Comment by ghik** [comment]
Sounds like a fun thing to do

**Comment by ghik** [comment]
I tried doing this and got blocked by https://github.com/lampepfl/dotty/issues/19480

**Comment by ghik** [comment]
Sure, but I haven't even gotten to porting the macro itself. I just tried to compile tests on Scala 3...

**Comment by KuceraMartin** [comment]
Actually I never tried compiling all the tests. Now that I did, I see I'm getting the same compiler crash as you.

I started by removing most tests and trying to write a macro that would generate something similar to what the Scala 2 `TableMacros` does, as per @lihaoyi's advice. You could try the same thing if you want. If you do so, you can cherry-pick this commit https://github.com/com-lihaoyi/scalasql/pull/3/commits/a96df75c0d56046dcc2ad5172b366b4526fd5af4 which fixes some trivial Scala 3 incompatibilities outside of macros. Then, delete all tests except for e.g. `Main.scala`. Then, if you just replace `TableMacros` with
```scala
trait TableMacros:
   given metadata[V[_[_]]]: Table.Metadata[V] = ???
```
it will at least compile. Later on, you can start adding some tests back. I tried multiple and never ran into that compiler crash. For instance `SqliteExample.scala` should work.

If you're interested in discussing it further, let's connect on Discord (mine is martin.kucera)

**Comment by ghik** [comment]
@KuceraMartin FYI https://github.com/lampepfl/dotty/issues/19480 already has a working fix on the way, I compiled the tests successfully with it

I'm going to take a break from this for now, but I'll be happy to discuss details if I come back to it.

**Comment by vvidlearn** [comment]
Hi this sounds like an interesting exercise. I am new to macros but consider this as an opportunity to learn them. So would like to work on it if its ok. Thank you.

**Comment by lihaoyi** [comment]
> Hi this sounds like an interesting exercise. I am new to macros but consider this as an opportunity to learn them. So would like to work on it if its ok. Thank you.

Please go ahead! No need to ask me for permission

**Comment by mrdziuban** [comment]
Hey @vvidlearn, are you still looking into this? I'm curious to look as well but don't want to step on your toes

**Comment by vvidlearn** [comment]
hi @mrdziuban sorry for the late reply, I am just a macro beginner. So it was beyond me. glad you completed it.
