### ISSUE TITLE
flatMap is unsafe

### ISSUE THREAD

**Issue by Katrix** [com-lihaoyi/scalasql#4]
Did a lot of thinking recently in my own library, and came to the conclusion that I could not implement flatMap safely for all SQL dialects. Wondered if ScalaSql was susceptible to the same, so I check, and yes. Here is an example of a query which will not run because of invalid syntax.

```scala
dbClient.renderSql(City.select.flatMap(c => City.select.sortBy(_.name).map(_ => c.id).crossJoin().map(r => r)))
```

**Comment by lihaoyi** [comment]
Going to call this a known limitation. For postgres you can use `.crossJoinLateral`, for other databases they just don't support this kind of subquery in a join
