### ISSUE TITLE
Call cancel() on statement?

### ISSUE THREAD

**Issue by aherlihy** [com-lihaoyi/scalasql#44]
Hi, I want to be able to cancel long-running queries. Using JDBC I would normally be able to call `statement.cancel()` but I can't figure out how to extract that from `db.run`. Any suggestions or workarounds would be very appreciated!

**Comment by aherlihy** [comment]
I tried changing:
```
db.run(<query>)
```
which works but I can't cancel, to
```
val str = db.renderSQL(<query>)
connection.createStatement().executeUpdate(str)
```
but I can't render the string, it fails with
```
java.sql.SQLException: Invalid Input Error: Parameter count mismatch
```
Can you suggest how to get the SQL string to at least render correctly? Thanks!

**Comment by lihaoyi** [comment]
Closing this since we discussed in person, probably was a result of using a prepared statement string with properly using `.prepareStatement` and setting the prepared statement variables
