### ISSUE TITLE
`GROUP BY` with more then one field is not supported

### ISSUE THREAD

**Issue by NPCRUS** [com-lihaoyi/scalasql#52]
using `City` model from `WorldSqlTests.scala`, such query compiles:
```scala
City.select
  .groupBy { t =>
    (t.id, t.countryCode)
  }(_.sumBy(_.population))
```
but if you **render** it run it, it throws following error:
```
scala.MatchError: an instance of class scala.collection.immutable.Vector1
scalasql.query.SimpleSelect.groupBy(SimpleSelect.scala:174)
```

**Comment by lihaoyi** [comment]
Seems like an oversight. Can probably be fixed by updating the relevant snippets (starting from the crashing line in the stack trace)
